# Generated by Django 2.2.1 on 2019-05-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
